name: Deploy Firebase Functions

on:
  push:
    paths:
      - "functions/**"
      - ".github/workflows/deploy-functions.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install functions deps
        working-directory: functions
        run: npm ci

      - name: Deploy functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
        run: firebase deploy --only functions --project "$PROJECT_ID"
